import { Question } from './question';
export const questionList: Question[] = [
    {id: 1, question: 'What is the difference between git pull and git fetch?'},
    {id: 2, question: 'How do I undo the most recent local commits in Git?'},
    {id: 3, question: 'How do I undo git add before commit?'},
    {id: 4, question: 'What and where are the stack and heap?'},
    {id: 5, question: 'How to make Git “forget” about a file that was tracked but is now in .gitignore?'},
    {id: 6, question: 'Tell what exactly do you know about GIT stash?'},
    {id: 7, question: ' What is the upper limit on the heads in the Gits?'},
    {id: 8, question: 'Can you put the Computer software and computer program separate from one another by a simple comparison?'},
    {id: 9, question: 'Is it possible in the Git to merge a branch into the master? How can you find the same?'},
    {id: 10, question: 'Name any two Git repository hosting services which are common'},
    {id: 11, question: 'What is conflict situation in the Git and how it can be solved?',},
    {id: 12, question: 'Do you think GitHub is batter as compared to Subversion of same? Why or why not?'},
    {id: 13, question: 'What language is considered in Git and what is the benefit of same in this approach according to you?'},
    {id: 14, question: 'Why is it advisable to create an additional commit rather than amending an existing commit?'},
    {id: 15, question: 'How will you know in GIT if a branch has been already merged into master?',},
    {id: 16, question: 'What is the difference between the ‘git diff ’and ‘git status’?'},
    {id: 17, question: 'What is ‘head’ in git and how many heads can be created in a repository?'},
    {id: 18, question: 'Why is it desirable to create an additional commit rather than amending an existing commit?',},
    {id: 19, question: 'How to remove a file from git without removing it from your file system?'},
    {id: 20, question: 'What is the difference between rebasing and merge in Git?'},
    {id: 21, question: 'How do you integrate Git with Jenkins?'},
    {id: 22, question:  'How to recover a deleted branch using git reflog?'},
    {id: 23, question: ' What are the benefits of using Version Control System?'},
    {id: 24, question: 'Mention the various Git repository hosting functions.'},
    {id: 25, question: 'What is ‘bare repository’ in Git?'},
    {id: 26, question: 'Name a few Git commands and explain their usage.'},
    {id: 27, question: 'Name the tool that can be deployed for Git migration?'},
    {id: 28, question: 'How much space do we get on GitHub?'},
    {id: 29, question: 'Are you familiar with the Git Clone?'},
    {id: 30, question: 'What is Gitlog and when you can use it?'},
  ];